#! usr/bin/env python3
# coding=utf-8

"""
This module imports Steam achievement data and creates a GUI display.

The data is accepted as a json file and written to the local folder as text.
This text file is used to create the graphical interface.

Alex Mote
"""
import json
import re
import requests
from graphics import Point, Rectangle, GraphWin, Text, color_rgb


class Achievement:
    """Basic achievement class."""

    def __init__(self, name, percent):
        """
        Create an Achievement object.

        Parameters
        ----------
        name : str
            The achievement's name.
        percent : str
            The percentage of global players who have unlocked it.

        """
        self.name = name
        self.percent = percent


def api_pull(steam_id):
    """
    Pull the global achievement stats from Steam's API.

    Parameters
    ----------
    steam_id : int
        The Steam Game ID whose achievements we wish to grab.

    Returns
    -------
    json.loads(response.text) : json
        Raw json data for the game's global achievements.

    """
    try:
        steam_id = int(steam_id)
    except ValueError:
        return f"Please enter a valid Steam ID.\n"
    else:
        url = f"http://api.steampowered.com/ISteamUserStats/GetGlobalAchievementPercentagesForApp/v0002/?gameid={steam_id}"
        response = requests.get(url, headers={"Accept": "application/json"})
        api_file = json.loads(response.text)
        if not api_file:
            return f"Please enter a valid Steam ID.\n"
        else:
            return api_file


def listifier(json_text, steam_id):
    """
    Turn a raw json file into a more readable text file.

    Parameters
    ----------
    json_text : json
        Raw json data generated by api_pull function.
    steam_id : int
        Steam Game ID inputted by user.

    Returns
    -------
    f"{steam_id}_achievements.txt" : file
        Filename of generated file; steam_id gives each game a unique file.

    """
    middle_man = json_text.get("achievementpercentages")  # Steam API is dumb
    ach_dlist = middle_man.get("achievements")
    ach_list = open(f"{steam_id}_achievements.txt", "w")
    for i in ach_dlist:
        ach_name = i.get("name")
        ach_per = i.get("percent")
        ach_list.write("{0}: {1:.2f}%\n".format(ach_name, ach_per))
    return f"{steam_id}_achievements.txt"


def tupler(ach_file):
    """
    Extract achievement data from a text file and create a list of tuples.

    Parameters
    ----------
    ach_file : file
        Achievement data file created by listifier function.

    Returns
    -------
    ach_tuples : list
        List of tuples; each tuple contains achievement name and percent.

    """
    ach_list = open(ach_file, "r")
    ach_data = ach_list.readlines()
    regex = r"(.*?): (.*?)%\n"
    ach_tuples = []
    for item in ach_data:
        ach_tuples.append(re.split(regex, item)[1:3])
    return ach_tuples


ACH_CLASSES = []


def classifier(ach_tuples):
    """
    Turn a list of tuples into a list of Achievement class objects.

    Parameters
    ----------
    ach_tuples : list
        List of tuples created by tupler function.

    Returns
    -------
    ach_classes : list
        List of Achievement class objects.

    """
    global ACH_CLASSES
    if len(ach_tuples) == 1:
        for name, percent in ach_tuples:
            ACH_CLASSES.append(Achievement(name, percent))
    else:
        classifier(ach_tuples[0:1])
        classifier(ach_tuples[1:])
    return ACH_CLASSES


def chart(ach_classes):
    """
    Create a chart of all Achievements, five at a time.

    Parameters
    ----------
    ach_classes : list
        A list of Achievement class objects.

    """
    if len(ach_classes) > 5:
        win = GraphWin("Achievement List", 500, 500)
        win.setBackground(color_rgb(200, 200, 200))

        Rectangle(Point(0, 0), Point(500, 80)).draw(win)
        Rectangle(Point(0, 80), Point(500, 160)).draw(win)
        Rectangle(Point(0, 160), Point(500, 240)).draw(win)
        Rectangle(Point(0, 240), Point(500, 320)).draw(win)
        Rectangle(Point(0, 320), Point(500, 400)).draw(win)
        fill_y = 0
        name_y = 55
        perc_y = 70

        for i in ach_classes[0:5]:
            i_fill = Rectangle(
                Point(0, fill_y), Point(5 * float(i.percent), fill_y + 80)
            )
            i_fill.setFill("green")
            i_fill.draw(win)

            Text(Point(250, name_y), i.name).draw(win)
            Text(Point(250, perc_y), f"{i.percent}%").draw(win)

            fill_y += 80
            name_y += 80
            perc_y += 80

        Text(Point(250, 450), "Click anywhere to continue...").draw(win)
        win.getMouse()
        win.close()
        del ach_classes[0:5]
        chart(ach_classes)
    else:
        win = GraphWin("Achievement List", 500, 500)
        win.setBackground(color_rgb(200, 200, 200))

        Rectangle(Point(0, 0), Point(500, 80)).draw(win)
        Rectangle(Point(0, 80), Point(500, 160)).draw(win)
        Rectangle(Point(0, 160), Point(500, 240)).draw(win)
        Rectangle(Point(0, 240), Point(500, 320)).draw(win)
        Rectangle(Point(0, 320), Point(500, 400)).draw(win)
        fill_y = 0
        name_y = 55
        perc_y = 70
        for i in ach_classes:
            i_fill = Rectangle(
                Point(0, fill_y), Point(5 * float(i.percent), fill_y + 80)
            )
            i_fill.setFill("green")
            i_fill.draw(win)

            Text(Point(250, name_y), i.name).draw(win)
            Text(Point(250, perc_y), f"{i.percent}%").draw(win)

            fill_y += 80
            name_y += 80
            perc_y += 80
        Text(Point(250, 450), "List complete. Click anywhere to close.").draw(win)
        win.getMouse()
        win.close()


def main():
    """Bring it all together, baby."""
    while True:
        steam_id = input("Please enter the Steam ID for the game you wish to view: ")
        api_file = api_pull(steam_id)
        if api_file == f"Please enter a valid Steam ID.\n":
            print(api_file)
            continue
        else:
            break
    ach_file = listifier(api_file, steam_id)
    ach_tuples = tupler(ach_file)
    ach_classlist = classifier(ach_tuples)
    chart(ach_classlist)


if __name__ == "__main__":
    main()
